### ISSUE TITLE
Back Arrow too Small

### ISSUE THREAD

**Issue by whatSocks** [peterklingelhofer/stream-app#14]
Not sure how to handle this navigation issue. Check image:
* Firefox
* Safari
* Expo app on iOS

little back arrow is just a dot on the Expo app

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/2731744/155241856-c45a3d6f-ed41-4aa2-b483-2fc1d5d0206d.png">

**Comment by peterklingelhofer** [comment]
Closing this and opening the issue in the repository it'll need to be handled in: https://github.com/resonatecoop/stream/issues/187
