### ISSUE TITLE
Smooth scrolling

### ISSUE THREAD

**Issue by glottis0q** [peterklingelhofer/stream-app#66]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I scroll and notice smooth scrolling is enabled. It feels unnatural and slow.

**Describe the solution you'd like**
I would like smooth scrolling to be disabled.

**Describe alternatives you've considered**
I considered the website but I thought using the app would be better for some reason.

**Additional context**
Unnecessary

**Comment by peterklingelhofer** [comment]
I'm guessing you're on Android?

At first glance, I would have though this issue pertains:
https://github.com/react-native-webview/react-native-webview/issues/1965

However, we don't have I'm not using `androidHardwareAccelerationDisabled`.

This app uses your phone's default browser, so if you have a way of disabling smooth scrolling in your phone's default browser, that would probably fix this issue. I don't have an Android myself so I've never run into this bug nor do I have a way to test it.

In the meantime, I will try to experiment with bumping the `react-native-webview` version to the latest to see if that solves that for you.

**Comment by peterklingelhofer** [comment]
https://github.com/peterklingelhofer/stream-app/releases/tag/react-native-webview-11.23 new release should be live in app stores in the next two days

**Comment by glottis0q** [comment]
I‘m on iOS 16.0 using the TestFlight version 1.2.0 (1.2.0)

**Comment by peterklingelhofer** [comment]
I noticed that iOS 16.0 is due to be released this fall (in beta). Sounds like this could be because you’re on an iOS beta release instead of a stable version? When you open https://stream.resonate.coop in Safari, do you have the same issue?

**Comment by glottis0q** [comment]
In Safari smooth scrolling isn't enabled. Its just fast and instant like most other webpages.

**Comment by peterklingelhofer** [comment]
I see, I think changing the [decelerationRate](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#decelerationrate) property to `normal` from `fast` could fix this - it seems that the default for Safari is `normal` but WebView defaults to `fast`. Creating a new build and submitting to Android/Apple Stores.

**Comment by glottis0q** [comment]
That fixed it. Great

**Comment by peterklingelhofer** [comment]
Awesome @glottis0q, glad we could get this fixed for you. 

Tagging the solution here for posterity: #69.

**Comment by ChenReuven** [comment]
> I see, I think changing the [decelerationRate](https://github.com/react-native-webview/react-native-webview/blob/master/docs/Reference.md#decelerationrate) property to `normal` from `fast` could fix this - it seems that the default for Safari is `normal` but WebView defaults to `fast`. Created a new [build](https://github.com/peterklingelhofer/stream-app/releases/tag/ios-deceleration-rate-normal) and submitted to Android/Apple Stores, should be available in the next 48 hours after it is through review.

Thanks, it help me a lot men :)
