### ISSUE TITLE
album art on now playing widget

### ISSUE THREAD

**Issue by whatSocks** [peterklingelhofer/stream-app#9]
Looks like a bit more could go on the now playing widget

https://github.com/tanguyantoine/react-native-music-control 
https://expo.canny.io/feature-requests/p/react-native-music-control

maybe i will give this a shot (unless you get to it first)

**Comment by peterklingelhofer** [comment]
I was looking at these earlier as well. I also noticed `react-native-webview` has an `injectedJavaScript` prop (example [here](https://idanlevi2.medium.com/injecting-javascript-into-react-native-webview-521e4e55964b)). Perhaps injecting JS that selects a hidden element with its value being JSON metadata which we could then parse in the component could work.

The fact that the iOS PWA fails to do this makes me curious if there's some way of making Safari report the now playing metadata the same way Chrome is on Android devices. I've done a bit of digging but haven't been able to come up with anything on that specific issue yet...

**Comment by peterklingelhofer** [comment]
[This link](https://stackoverflow.com/questions/44418606/how-do-i-set-a-thumbnail-when-playing-audio-in-ios-safari) discusses the issue, but it's a little out of date.

**Comment by peterklingelhofer** [comment]
[BrowserCompatibility](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession#browser_compatibility) for the [MediaSessionAPI](https://web.dev/media-session/) seems to be pretty well supported now in 2022. I may make an issue for this on the [stream repo](https://github.com/resonatecoop/stream) later this week and attempt. I suspect this would be far easier to get going on that side than making the stream repo somehow respond to WebView and inform it what it's playing, but I could be wrong.

**Comment by peterklingelhofer** [comment]
It's working perfectly fine in the web app in my Desktop Safari, which is up to date, for example:
<img width="867" alt="Screen Shot 2022-02-24 at 12 20 01 AM" src="https://user-images.githubusercontent.com/60944077/155469213-ed408a48-05e9-4fba-846c-4e427840becc.png">

**Comment by peterklingelhofer** [comment]
Per [MDN's MediaSessionAPI Browser Compatibility](https://developer.mozilla.org/en-US/docs/Web/API/MediaSession#browser_compatibility), iOS 15 is required for full functionality of this feature. I updated my phone and voilà, we're officially in business! As a result, I am closing this issue.

![IMG_684FB2069995-1](https://user-images.githubusercontent.com/60944077/155626074-05084c42-5ce2-4ac0-a4a7-2ad438871d04.jpeg)
